import Airtable from 'airtable';
import Head from 'next/head';
import Link from 'next/link'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export async function getStaticProps() {
  const airtable = new Airtable({
    apiKey: process.env.API_KEY,
    view: 'Name',
  });

  const records = await airtable
    .base(process.env.BASE_ID)('Directory')
    .select({
      fields: ['Name', 'Heads', 'Instagram', 'Status', 'Category', 'About', 'Colour', 'Image'],
      view: 'Name',
    })
    .all();

  const products = records.map((sig) => {

    return {
      name: sig.get('Name'),
      type: sig.get('Name'),
      category: sig.get('Category'),
      link: sig.get('Instagram'),
      status: sig.get('Status'),
      about: sig.get('About'),
      heads: sig.get('Heads'),
      colour: sig.get('Colour'),
      image: sig.get('Image'),
    };
  });

  return {
    props: {
      products,
    },
    revalidate: 30,
  };
}


function Product({ name, type, about, colour, heads, image, status, category, link }) {
  
    return (
    <div className="max-w-sm bg-white rounded-lg border m-3 border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
    <div className="p-5">
        <a href="#"
        style={{
          display: 'flex',
        }}
        >
            <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{name}</h5>
<div>

 <button className="px-2 mx-2 py-0 -translate-y-0.5 my-2 opacity-0.8 hover:bg-yellow-600 bg-green-500 text-white text-sm font-medium rounded-full" >
    {status}
 </button>
 </div>
        </a>

        <p className="mb-3 font-normal text-gray-700 dark:text-gray-400"><i>{category}</i></p>
        <p className="mb-3 font-normal text-gray-700 dark:text-gray-300">{about}</p>
        <a href="#" className="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            Read more
            <svg className="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
        </a>
    </div>
</div>
  );
}

export default function Clubs({ products }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Turner Fenton Secondary School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <section className="pt-20 lg:pt-[120px] pb-5 lg:pb-5">
   <div className="container">
      <div className="flex flex-wrap justify-center -mx-4">
         <div className="w-full px-4">
            <div className="text-center mx-auto mb-[60px] lg:mb-20 max-w-[510px]">
               <h2
                  className="
                  font-bold
                  text-3xl
                  sm:text-4xl
                  md:text-[40px]
                  text-white
                  mb-4
                  "
                  >
                 Discover Turner Fenton
               </h2>
               <div className="display-flex">
               <button className="text-white p-3 "><Link href="/clubs=name">Name</Link></button>
               <button className="text-white p-3"> <Link href="/clubs=status">Status</Link></button>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
        

        <div className={styles.grid}>

        {products.map((sig) => (
          <Product
            key={sig.name}
            name={sig.name}
            type={sig.name}
            category={sig.category}
            link={sig.link}
            heads={sig.heads}
            status={sig.status}
            about={sig.about}
            colour={sig.colour}
            image={sig.image}
          />    
        ))}
        </div>

        
      </main>
    </div>
  )
}

