import Airtable from 'airtable';
import Head from 'next/head';
import Link from 'next/link'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export async function getStaticProps() {
  const airtable = new Airtable({
    apiKey: process.env.API_KEY,
    view: 'Grid View',
  });

  const records = await airtable
    .base(process.env.BASE_ID)('Blog')
    .select({
      fields: ['Title', 'Description', 'Content'],
      view: 'Grid view',
    })
    .all();
 
  const products = records.map((sig) => {
    return {
      title: sig.get('Title'),
      description: sig.get('Description'),
      content: sig.get('Content'),
    };
  });

  return {
    props: {
      products,
    },
    revalidate: 30,
  };
}


function Product({ title, description, content }) {
  return (
    <div className='p-5'>
        <a href="#" className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{title}</h5>
    <p className="font-normal text-gray-700 dark:text-gray-400">{description}</p>
</a>
    </div>
  );
}

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Turner Fenton Secondary School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <section className="pt-20 lg:pt-[120px] pb-5 lg:pb-5">
   <div className="container">
      <div className="flex flex-wrap justify-center -mx-4">
         <div className="w-full px-4">
            <div className="text-center mx-auto mb-[60px] lg:mb-20 max-w-[510px]">
               <h2
                  className="
                  font-bold
                  text-3xl
                  sm:text-4xl
                  md:text-[40px]
                  text-white
                  mb-4
                  "
                  >
                 Discover Turner Fenton
               </h2>
            </div>
         </div>
      </div>
   </div>
</section>
        

        <div className={styles.bloggrid}>

        {products.map((sig) => (
          <Product
            key={sig.title}
            title={sig.title}
            content={sig.content}
            description={sig.description}
          />    
        ))}
        </div>

        
      </main>
    </div>
  )
}

